package com.yixianqian.entities;

import java.util.List;
import com.yixianqian.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.yixianqian.dao.CityDao;
import com.yixianqian.dao.ProvinceDao;
import com.yixianqian.dao.SchoolDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CITY.
 */
public class City {

    private Long id;
    private Long cityID;
    private String cityName;
    private long provinceID;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient CityDao myDao;

    private Province province;
    private Long province__resolvedKey;

    private List<School> schoolList;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public City() {
    }

    public City(Long id) {
        this.id = id;
    }

    public City(Long id, Long cityID, String cityName, long provinceID) {
        this.id = id;
        this.cityID = cityID;
        this.cityName = cityName;
        this.provinceID = provinceID;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getCityDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCityID() {
        return cityID;
    }

    public void setCityID(Long cityID) {
        this.cityID = cityID;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public long getProvinceID() {
        return provinceID;
    }

    public void setProvinceID(long provinceID) {
        this.provinceID = provinceID;
    }

    /** To-one relationship, resolved on first access. */
    public Province getProvince() {
        long __key = this.provinceID;
        if (province__resolvedKey == null || !province__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ProvinceDao targetDao = daoSession.getProvinceDao();
            Province provinceNew = targetDao.load(__key);
            synchronized (this) {
                province = provinceNew;
            	province__resolvedKey = __key;
            }
        }
        return province;
    }

    public void setProvince(Province province) {
        if (province == null) {
            throw new DaoException("To-one property 'provinceID' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.province = province;
            provinceID = province.getId();
            province__resolvedKey = provinceID;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<School> getSchoolList() {
        if (schoolList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            SchoolDao targetDao = daoSession.getSchoolDao();
            List<School> schoolListNew = targetDao._queryCity_SchoolList(id);
            synchronized (this) {
                if(schoolList == null) {
                    schoolList = schoolListNew;
                }
            }
        }
        return schoolList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetSchoolList() {
        schoolList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
