package com.yixianqian.entities;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CONVERSATION.
 */
public class Conversation {

    private Long id;
    private Long userID;
    private String name;
    private String smallAvatar;
    private String lastMessage;
    private Integer newNum;
    private Long time;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Conversation() {
    }

    public Conversation(Long id) {
        this.id = id;
    }

    public Conversation(Long id, Long userID, String name, String smallAvatar, String lastMessage, Integer newNum, Long time) {
        this.id = id;
        this.userID = userID;
        this.name = name;
        this.smallAvatar = smallAvatar;
        this.lastMessage = lastMessage;
        this.newNum = newNum;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserID() {
        return userID;
    }

    public void setUserID(Long userID) {
        this.userID = userID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSmallAvatar() {
        return smallAvatar;
    }

    public void setSmallAvatar(String smallAvatar) {
        this.smallAvatar = smallAvatar;
    }

    public String getLastMessage() {
        return lastMessage;
    }

    public void setLastMessage(String lastMessage) {
        this.lastMessage = lastMessage;
    }

    public Integer getNewNum() {
        return newNum;
    }

    public void setNewNum(Integer newNum) {
        this.newNum = newNum;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
