package com.yixianqian.entities;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table FLIPPER.
 */
public class Flipper {

    private Long id;
    private Integer userID;
    private String nickname;
    private String realname;
    private String gender;
    private String email;
    private String largeAvatar;
    private String samllAvatar;
    private String bloodType;
    private String constell;
    private String introduce;
    private java.util.Date birthday;
    private java.util.Date time;
    private Integer age;
    private Integer vocationID;
    private Integer stateID;
    private Integer provinceID;
    private Integer cityID;
    private Integer schoolID;
    private Integer height;
    private Integer weight;
    private Integer imagePass;
    private Double salary;
    private Boolean isRead;
    private String tel;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Flipper() {
    }

    public Flipper(Long id) {
        this.id = id;
    }

    public Flipper(Long id, Integer userID, String nickname, String realname, String gender, String email, String largeAvatar, String samllAvatar, String bloodType, String constell, String introduce, java.util.Date birthday, java.util.Date time, Integer age, Integer vocationID, Integer stateID, Integer provinceID, Integer cityID, Integer schoolID, Integer height, Integer weight, Integer imagePass, Double salary, Boolean isRead, String tel) {
        this.id = id;
        this.userID = userID;
        this.nickname = nickname;
        this.realname = realname;
        this.gender = gender;
        this.email = email;
        this.largeAvatar = largeAvatar;
        this.samllAvatar = samllAvatar;
        this.bloodType = bloodType;
        this.constell = constell;
        this.introduce = introduce;
        this.birthday = birthday;
        this.time = time;
        this.age = age;
        this.vocationID = vocationID;
        this.stateID = stateID;
        this.provinceID = provinceID;
        this.cityID = cityID;
        this.schoolID = schoolID;
        this.height = height;
        this.weight = weight;
        this.imagePass = imagePass;
        this.salary = salary;
        this.isRead = isRead;
        this.tel = tel;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUserID() {
        return userID;
    }

    public void setUserID(Integer userID) {
        this.userID = userID;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getRealname() {
        return realname;
    }

    public void setRealname(String realname) {
        this.realname = realname;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getLargeAvatar() {
        return largeAvatar;
    }

    public void setLargeAvatar(String largeAvatar) {
        this.largeAvatar = largeAvatar;
    }

    public String getSamllAvatar() {
        return samllAvatar;
    }

    public void setSamllAvatar(String samllAvatar) {
        this.samllAvatar = samllAvatar;
    }

    public String getBloodType() {
        return bloodType;
    }

    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }

    public String getConstell() {
        return constell;
    }

    public void setConstell(String constell) {
        this.constell = constell;
    }

    public String getIntroduce() {
        return introduce;
    }

    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    public java.util.Date getBirthday() {
        return birthday;
    }

    public void setBirthday(java.util.Date birthday) {
        this.birthday = birthday;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Integer getVocationID() {
        return vocationID;
    }

    public void setVocationID(Integer vocationID) {
        this.vocationID = vocationID;
    }

    public Integer getStateID() {
        return stateID;
    }

    public void setStateID(Integer stateID) {
        this.stateID = stateID;
    }

    public Integer getProvinceID() {
        return provinceID;
    }

    public void setProvinceID(Integer provinceID) {
        this.provinceID = provinceID;
    }

    public Integer getCityID() {
        return cityID;
    }

    public void setCityID(Integer cityID) {
        this.cityID = cityID;
    }

    public Integer getSchoolID() {
        return schoolID;
    }

    public void setSchoolID(Integer schoolID) {
        this.schoolID = schoolID;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Integer getWeight() {
        return weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    public Integer getImagePass() {
        return imagePass;
    }

    public void setImagePass(Integer imagePass) {
        this.imagePass = imagePass;
    }

    public Double getSalary() {
        return salary;
    }

    public void setSalary(Double salary) {
        this.salary = salary;
    }

    public Boolean getIsRead() {
        return isRead;
    }

    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
