package com.yixianqian.entities;

import com.yixianqian.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.yixianqian.dao.CityDao;
import com.yixianqian.dao.ProvinceDao;
import com.yixianqian.dao.SchoolDao;
import com.yixianqian.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long userID;
    private String bpushUserID;
    private String bpushChannelID;
    private String nickname;
    private String realname;
    private String password;
    private String gender;
    private String tel;
    private String email;
    private String large_avatar;
    private String small_avatar;
    private String address;
    private String blood_type;
    private String constell;
    private String introduce;
    private Integer age;
    private Integer vocationid;
    private Integer stateid;
    private Integer height;
    private Integer weight;
    private Integer image_pass;
    private Double salary;
    private java.util.Date birthday;
    private long schoolID;
    private long cityID;
    private long provinceID;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient UserDao myDao;

    private School school;
    private Long school__resolvedKey;

    private City city;
    private Long city__resolvedKey;

    private Province province;
    private Long province__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public User() {
    }

    public User(Long userID, String bpushUserID, String bpushChannelID, String nickname, String realname, String password, String gender, String tel, String email, String large_avatar, String small_avatar, String address, String blood_type, String constell, String introduce, Integer age, Integer vocationid, Integer stateid, Integer height, Integer weight, Integer image_pass, Double salary, java.util.Date birthday, long schoolID, long cityID, long provinceID) {
        this.userID = userID;
        this.bpushUserID = bpushUserID;
        this.bpushChannelID = bpushChannelID;
        this.nickname = nickname;
        this.realname = realname;
        this.password = password;
        this.gender = gender;
        this.tel = tel;
        this.email = email;
        this.large_avatar = large_avatar;
        this.small_avatar = small_avatar;
        this.address = address;
        this.blood_type = blood_type;
        this.constell = constell;
        this.introduce = introduce;
        this.age = age;
        this.vocationid = vocationid;
        this.stateid = stateid;
        this.height = height;
        this.weight = weight;
        this.image_pass = image_pass;
        this.salary = salary;
        this.birthday = birthday;
        this.schoolID = schoolID;
        this.cityID = cityID;
        this.provinceID = provinceID;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getUserDao() : null;
    }

    public Long getUserID() {
        return userID;
    }

    public void setUserID(Long userID) {
        this.userID = userID;
    }

    public String getBpushUserID() {
        return bpushUserID;
    }

    public void setBpushUserID(String bpushUserID) {
        this.bpushUserID = bpushUserID;
    }

    public String getBpushChannelID() {
        return bpushChannelID;
    }

    public void setBpushChannelID(String bpushChannelID) {
        this.bpushChannelID = bpushChannelID;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getRealname() {
        return realname;
    }

    public void setRealname(String realname) {
        this.realname = realname;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getLarge_avatar() {
        return large_avatar;
    }

    public void setLarge_avatar(String large_avatar) {
        this.large_avatar = large_avatar;
    }

    public String getSmall_avatar() {
        return small_avatar;
    }

    public void setSmall_avatar(String small_avatar) {
        this.small_avatar = small_avatar;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getBlood_type() {
        return blood_type;
    }

    public void setBlood_type(String blood_type) {
        this.blood_type = blood_type;
    }

    public String getConstell() {
        return constell;
    }

    public void setConstell(String constell) {
        this.constell = constell;
    }

    public String getIntroduce() {
        return introduce;
    }

    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Integer getVocationid() {
        return vocationid;
    }

    public void setVocationid(Integer vocationid) {
        this.vocationid = vocationid;
    }

    public Integer getStateid() {
        return stateid;
    }

    public void setStateid(Integer stateid) {
        this.stateid = stateid;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Integer getWeight() {
        return weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    public Integer getImage_pass() {
        return image_pass;
    }

    public void setImage_pass(Integer image_pass) {
        this.image_pass = image_pass;
    }

    public Double getSalary() {
        return salary;
    }

    public void setSalary(Double salary) {
        this.salary = salary;
    }

    public java.util.Date getBirthday() {
        return birthday;
    }

    public void setBirthday(java.util.Date birthday) {
        this.birthday = birthday;
    }

    public long getSchoolID() {
        return schoolID;
    }

    public void setSchoolID(long schoolID) {
        this.schoolID = schoolID;
    }

    public long getCityID() {
        return cityID;
    }

    public void setCityID(long cityID) {
        this.cityID = cityID;
    }

    public long getProvinceID() {
        return provinceID;
    }

    public void setProvinceID(long provinceID) {
        this.provinceID = provinceID;
    }

    /** To-one relationship, resolved on first access. */
    public School getSchool() {
        long __key = this.schoolID;
        if (school__resolvedKey == null || !school__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            SchoolDao targetDao = daoSession.getSchoolDao();
            School schoolNew = targetDao.load(__key);
            synchronized (this) {
                school = schoolNew;
            	school__resolvedKey = __key;
            }
        }
        return school;
    }

    public void setSchool(School school) {
        if (school == null) {
            throw new DaoException("To-one property 'schoolID' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.school = school;
            schoolID = school.getId();
            school__resolvedKey = schoolID;
        }
    }

    /** To-one relationship, resolved on first access. */
    public City getCity() {
        long __key = this.cityID;
        if (city__resolvedKey == null || !city__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            CityDao targetDao = daoSession.getCityDao();
            City cityNew = targetDao.load(__key);
            synchronized (this) {
                city = cityNew;
            	city__resolvedKey = __key;
            }
        }
        return city;
    }

    public void setCity(City city) {
        if (city == null) {
            throw new DaoException("To-one property 'cityID' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.city = city;
            cityID = city.getId();
            city__resolvedKey = cityID;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Province getProvince() {
        long __key = this.provinceID;
        if (province__resolvedKey == null || !province__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ProvinceDao targetDao = daoSession.getProvinceDao();
            Province provinceNew = targetDao.load(__key);
            synchronized (this) {
                province = provinceNew;
            	province__resolvedKey = __key;
            }
        }
        return province;
    }

    public void setProvince(Province province) {
        if (province == null) {
            throw new DaoException("To-one property 'provinceID' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.province = province;
            provinceID = province.getId();
            province__resolvedKey = provinceID;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
