package com.yixianqian.entities;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table VOCATION.
 */
public class Vocation {

    private Long id;
    private String vocationName;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Vocation() {
    }

    public Vocation(Long id) {
        this.id = id;
    }

    public Vocation(Long id, String vocationName) {
        this.id = id;
        this.vocationName = vocationName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getVocationName() {
        return vocationName;
    }

    public void setVocationName(String vocationName) {
        this.vocationName = vocationName;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
