package com.yixianqian.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.yixianqian.entities.Flipper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FLIPPER.
*/
public class FlipperDao extends AbstractDao<Flipper, Long> {

    public static final String TABLENAME = "FLIPPER";

    /**
     * Properties of entity Flipper.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserID = new Property(1, Integer.class, "userID", false, "USER_ID");
        public final static Property BpushUserID = new Property(2, String.class, "bpushUserID", false, "BPUSH_USER_ID");
        public final static Property BpushChannelID = new Property(3, String.class, "bpushChannelID", false, "BPUSH_CHANNEL_ID");
        public final static Property Nickname = new Property(4, String.class, "nickname", false, "NICKNAME");
        public final static Property Realname = new Property(5, String.class, "realname", false, "REALNAME");
        public final static Property Gender = new Property(6, String.class, "gender", false, "GENDER");
        public final static Property Email = new Property(7, String.class, "email", false, "EMAIL");
        public final static Property LargeAvatar = new Property(8, String.class, "largeAvatar", false, "LARGE_AVATAR");
        public final static Property SamllAvatar = new Property(9, String.class, "samllAvatar", false, "SAMLL_AVATAR");
        public final static Property BloodType = new Property(10, String.class, "bloodType", false, "BLOOD_TYPE");
        public final static Property Constell = new Property(11, String.class, "constell", false, "CONSTELL");
        public final static Property Introduce = new Property(12, String.class, "introduce", false, "INTRODUCE");
        public final static Property Birthday = new Property(13, java.util.Date.class, "birthday", false, "BIRTHDAY");
        public final static Property Time = new Property(14, java.util.Date.class, "time", false, "TIME");
        public final static Property Age = new Property(15, Integer.class, "age", false, "AGE");
        public final static Property VocationID = new Property(16, Integer.class, "vocationID", false, "VOCATION_ID");
        public final static Property StateID = new Property(17, Integer.class, "stateID", false, "STATE_ID");
        public final static Property ProvinceID = new Property(18, Integer.class, "provinceID", false, "PROVINCE_ID");
        public final static Property CityID = new Property(19, Integer.class, "cityID", false, "CITY_ID");
        public final static Property SchoolID = new Property(20, Integer.class, "schoolID", false, "SCHOOL_ID");
        public final static Property Height = new Property(21, Integer.class, "height", false, "HEIGHT");
        public final static Property Weight = new Property(22, Integer.class, "weight", false, "WEIGHT");
        public final static Property ImagePass = new Property(23, Integer.class, "imagePass", false, "IMAGE_PASS");
        public final static Property Salary = new Property(24, Double.class, "salary", false, "SALARY");
        public final static Property IsRead = new Property(25, Boolean.class, "isRead", false, "IS_READ");
        public final static Property Tel = new Property(26, String.class, "tel", false, "TEL");
        public final static Property Status = new Property(27, String.class, "status", false, "STATUS");
        public final static Property Type = new Property(28, Integer.class, "type", false, "TYPE");
    };


    public FlipperDao(DaoConfig config) {
        super(config);
    }
    
    public FlipperDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FLIPPER' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'USER_ID' INTEGER," + // 1: userID
                "'BPUSH_USER_ID' TEXT," + // 2: bpushUserID
                "'BPUSH_CHANNEL_ID' TEXT," + // 3: bpushChannelID
                "'NICKNAME' TEXT," + // 4: nickname
                "'REALNAME' TEXT," + // 5: realname
                "'GENDER' TEXT," + // 6: gender
                "'EMAIL' TEXT," + // 7: email
                "'LARGE_AVATAR' TEXT," + // 8: largeAvatar
                "'SAMLL_AVATAR' TEXT," + // 9: samllAvatar
                "'BLOOD_TYPE' TEXT," + // 10: bloodType
                "'CONSTELL' TEXT," + // 11: constell
                "'INTRODUCE' TEXT," + // 12: introduce
                "'BIRTHDAY' INTEGER," + // 13: birthday
                "'TIME' INTEGER," + // 14: time
                "'AGE' INTEGER," + // 15: age
                "'VOCATION_ID' INTEGER," + // 16: vocationID
                "'STATE_ID' INTEGER," + // 17: stateID
                "'PROVINCE_ID' INTEGER," + // 18: provinceID
                "'CITY_ID' INTEGER," + // 19: cityID
                "'SCHOOL_ID' INTEGER," + // 20: schoolID
                "'HEIGHT' INTEGER," + // 21: height
                "'WEIGHT' INTEGER," + // 22: weight
                "'IMAGE_PASS' INTEGER," + // 23: imagePass
                "'SALARY' REAL," + // 24: salary
                "'IS_READ' INTEGER," + // 25: isRead
                "'TEL' TEXT," + // 26: tel
                "'STATUS' TEXT," + // 27: status
                "'TYPE' INTEGER);"); // 28: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FLIPPER'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Flipper entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer userID = entity.getUserID();
        if (userID != null) {
            stmt.bindLong(2, userID);
        }
 
        String bpushUserID = entity.getBpushUserID();
        if (bpushUserID != null) {
            stmt.bindString(3, bpushUserID);
        }
 
        String bpushChannelID = entity.getBpushChannelID();
        if (bpushChannelID != null) {
            stmt.bindString(4, bpushChannelID);
        }
 
        String nickname = entity.getNickname();
        if (nickname != null) {
            stmt.bindString(5, nickname);
        }
 
        String realname = entity.getRealname();
        if (realname != null) {
            stmt.bindString(6, realname);
        }
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(7, gender);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(8, email);
        }
 
        String largeAvatar = entity.getLargeAvatar();
        if (largeAvatar != null) {
            stmt.bindString(9, largeAvatar);
        }
 
        String samllAvatar = entity.getSamllAvatar();
        if (samllAvatar != null) {
            stmt.bindString(10, samllAvatar);
        }
 
        String bloodType = entity.getBloodType();
        if (bloodType != null) {
            stmt.bindString(11, bloodType);
        }
 
        String constell = entity.getConstell();
        if (constell != null) {
            stmt.bindString(12, constell);
        }
 
        String introduce = entity.getIntroduce();
        if (introduce != null) {
            stmt.bindString(13, introduce);
        }
 
        java.util.Date birthday = entity.getBirthday();
        if (birthday != null) {
            stmt.bindLong(14, birthday.getTime());
        }
 
        java.util.Date time = entity.getTime();
        if (time != null) {
            stmt.bindLong(15, time.getTime());
        }
 
        Integer age = entity.getAge();
        if (age != null) {
            stmt.bindLong(16, age);
        }
 
        Integer vocationID = entity.getVocationID();
        if (vocationID != null) {
            stmt.bindLong(17, vocationID);
        }
 
        Integer stateID = entity.getStateID();
        if (stateID != null) {
            stmt.bindLong(18, stateID);
        }
 
        Integer provinceID = entity.getProvinceID();
        if (provinceID != null) {
            stmt.bindLong(19, provinceID);
        }
 
        Integer cityID = entity.getCityID();
        if (cityID != null) {
            stmt.bindLong(20, cityID);
        }
 
        Integer schoolID = entity.getSchoolID();
        if (schoolID != null) {
            stmt.bindLong(21, schoolID);
        }
 
        Integer height = entity.getHeight();
        if (height != null) {
            stmt.bindLong(22, height);
        }
 
        Integer weight = entity.getWeight();
        if (weight != null) {
            stmt.bindLong(23, weight);
        }
 
        Integer imagePass = entity.getImagePass();
        if (imagePass != null) {
            stmt.bindLong(24, imagePass);
        }
 
        Double salary = entity.getSalary();
        if (salary != null) {
            stmt.bindDouble(25, salary);
        }
 
        Boolean isRead = entity.getIsRead();
        if (isRead != null) {
            stmt.bindLong(26, isRead ? 1l: 0l);
        }
 
        String tel = entity.getTel();
        if (tel != null) {
            stmt.bindString(27, tel);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(28, status);
        }
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(29, type);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Flipper readEntity(Cursor cursor, int offset) {
        Flipper entity = new Flipper( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // userID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // bpushUserID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // bpushChannelID
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // nickname
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // realname
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // gender
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // email
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // largeAvatar
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // samllAvatar
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // bloodType
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // constell
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // introduce
            cursor.isNull(offset + 13) ? null : new java.util.Date(cursor.getLong(offset + 13)), // birthday
            cursor.isNull(offset + 14) ? null : new java.util.Date(cursor.getLong(offset + 14)), // time
            cursor.isNull(offset + 15) ? null : cursor.getInt(offset + 15), // age
            cursor.isNull(offset + 16) ? null : cursor.getInt(offset + 16), // vocationID
            cursor.isNull(offset + 17) ? null : cursor.getInt(offset + 17), // stateID
            cursor.isNull(offset + 18) ? null : cursor.getInt(offset + 18), // provinceID
            cursor.isNull(offset + 19) ? null : cursor.getInt(offset + 19), // cityID
            cursor.isNull(offset + 20) ? null : cursor.getInt(offset + 20), // schoolID
            cursor.isNull(offset + 21) ? null : cursor.getInt(offset + 21), // height
            cursor.isNull(offset + 22) ? null : cursor.getInt(offset + 22), // weight
            cursor.isNull(offset + 23) ? null : cursor.getInt(offset + 23), // imagePass
            cursor.isNull(offset + 24) ? null : cursor.getDouble(offset + 24), // salary
            cursor.isNull(offset + 25) ? null : cursor.getShort(offset + 25) != 0, // isRead
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // tel
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // status
            cursor.isNull(offset + 28) ? null : cursor.getInt(offset + 28) // type
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Flipper entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserID(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setBpushUserID(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBpushChannelID(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNickname(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setRealname(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setGender(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setEmail(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setLargeAvatar(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSamllAvatar(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setBloodType(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setConstell(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setIntroduce(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setBirthday(cursor.isNull(offset + 13) ? null : new java.util.Date(cursor.getLong(offset + 13)));
        entity.setTime(cursor.isNull(offset + 14) ? null : new java.util.Date(cursor.getLong(offset + 14)));
        entity.setAge(cursor.isNull(offset + 15) ? null : cursor.getInt(offset + 15));
        entity.setVocationID(cursor.isNull(offset + 16) ? null : cursor.getInt(offset + 16));
        entity.setStateID(cursor.isNull(offset + 17) ? null : cursor.getInt(offset + 17));
        entity.setProvinceID(cursor.isNull(offset + 18) ? null : cursor.getInt(offset + 18));
        entity.setCityID(cursor.isNull(offset + 19) ? null : cursor.getInt(offset + 19));
        entity.setSchoolID(cursor.isNull(offset + 20) ? null : cursor.getInt(offset + 20));
        entity.setHeight(cursor.isNull(offset + 21) ? null : cursor.getInt(offset + 21));
        entity.setWeight(cursor.isNull(offset + 22) ? null : cursor.getInt(offset + 22));
        entity.setImagePass(cursor.isNull(offset + 23) ? null : cursor.getInt(offset + 23));
        entity.setSalary(cursor.isNull(offset + 24) ? null : cursor.getDouble(offset + 24));
        entity.setIsRead(cursor.isNull(offset + 25) ? null : cursor.getShort(offset + 25) != 0);
        entity.setTel(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setStatus(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setType(cursor.isNull(offset + 28) ? null : cursor.getInt(offset + 28));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Flipper entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Flipper entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
